../donemodel/new_sticker_model0250.pt
['0', '1', '10', '11', '13', '14', '15', '16', '2', '3', '4', '5', '6', '7', '8', '9']
{'train': 3509, 'val': 1148, 'test': 40}
Traceback (most recent call last):
  File "sticker_retrain.py", line 112, in <module>
    model_ft.load_state_dict(torch.load('../donemodel/'+args.model))
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 505, in persistent_load
    data_type(size), location)
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 114, in default_restore_location
    result = fn(storage, location)
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/project/compute/seas-lab-vorobeychik/anaconda3/envs/torch/lib/python3.7/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
